services:
  back-end:
    build: ./back-end
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/back-end
    command: bash -c "cd backend && python manage.py runserver 0.0.0.0:8000"
  
  front-end:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/front-end